### ISSUE TITLE
Relate Paper

### ISSUE THREAD

**Issue by chengwei0427** [Grandzxw/AWG-NET#1]
Hi, @Grandzxw 
Congratulations.
Can you upload the relate paper [Multi-Modal Features and Accurate Place Recognition with Robust Optimization for Lidar-Visual-Inertial SLAM](https://ieeexplore.ieee.org/document/10445759)

**Comment by Grandzxw** [comment]
> Hi, @Grandzxw Congratulations. Can you upload the relate paper [Multi-Modal Features and Accurate Place Recognition with Robust Optimization for Lidar-Visual-Inertial SLAM](https://ieeexplore.ieee.org/document/10445759)

Do you mean the relate paper or code?

**Comment by chengwei0427** [comment]
Relate paper and code.

**Comment by Grandzxw** [comment]
> Relate paper and code.

Since it's still in early access, I cannot upload the PDF to GitHub, or you can provide your email and I'll send it to you via email.

**Comment by chengwei0427** [comment]
ok . qq-email: 960732491@qq.com

**Comment by Grandzxw** [comment]
> ok . qq-email: [960732491@qq.com](mailto:960732491@qq.com)

I have send it

**Comment by chengwei0427** [comment]
Get, thanks.
